PLAYLIST_LIST = [
    #{"name":"Top 50 : Monde","id":"37i9dQZEVXbMDoHDwVN2tF"},
    {"name":"African Heat","id":"37i9dQZF1DWYkaDif7Ztbp"},
    {"name":"Viral 50 : Monde","id":"37i9dQZEVXbLiRSasKsNU9"},
    {"name":"RapCaviar","id":"37i9dQZF1DX0XUsuxWHRQd"},
    {"name":"Today's Top Hits","id":"37i9dQZF1DXcBWIGoYBM5M"},
    {"name":"RNB X","id":"37i9dQZF1DX4SBhb3fqCJd"},
    {"name":"New Music Friday","id":"37i9dQZF1DWXJfnUiYjUKT"},
    {"name":"Peaceful Piano","id":"37i9dQZF1DX4sWSpwq3LiO"},
    {"name":"Hot Country","id":"37i9dQZF1DX1lVhptIYRda"},
    {"name": "Radio Dadju", "id":"37i9dQZF1E4yPDkJVLhqxP"},
    {"name": "Playlist Bonne humeur | Hits feel good", "id":"131wVohjHrpv3U321ZzFzD"},
    {"name": "PLAYLIST SOIREE 2024","id":"42ANQDe3MPMphzdreeFYdQ"},
    {"name": "Favorite Playlists", "id":"7M7YcWC3N6cdCAuIgqMmSl"},
    {"name": "Playlist 80,90's", "id":"2yckJMhl7T8QkW0sDlYwY1"},
    {"name": "BEST AFROBEATS PLAYLISTS", "id":"0wlGLK1R89ekpIrKQFFVrF"},
    {"name": "Rock Playlists", "id":"0xTOjQjzCBKB8xLsU9XNlb"},
    {"name": "Playlists for when you're in love", "id":"1Y9PH7gPFxJgwB9DqFBxwL"},
    {"name": "Rumba Congolaise-TOP 50 Hits 2022-DjVTR Mariage mixte", "id":"4HsoAsM7pkzOaKodCqSwv3"},
    {"name": "PLAYLIST ETE RAP 2023", "id":"3qbBI2v0FgdOJw4C61To4q"},
    {"name": "This Is Tayc", "id":"37i9dQZF1DZ06evO4iQm8l"},
    {"name": "This Is Damso", "id":"37i9dQZF1DZ06evO1G9baM"},
    {"name": "This Is Davido", "id":"37i9dQZF1DZ06evO0vEAMw"},
    {"name": "PVNCHLNRS", "id":"37i9dQZF1DX1X23oiQRTB5"},
    {"name": "Akon:Best Of The Best", "id":"7l3aIpgOLDBuTjx4FrlhHI"},
    {"name": "Playlists to listen to when you're high or drunk", "id":"4HxUICsvK1bV5DBzQbxjQq"},
    {"name": "African Hits 2023", "id":"4ZtmMuXoeI14XT7pubLq70"},
    {"name": "This Is Toofan", "id":"37i9dQZF1DZ06evO3it0ps"},
    {"name": "Dancehall Official", "id":"37i9dQZF1DXan38dNVDdl4"},
    {"name": "Playlist Allenamento 2024", "id":"0YQV3sSE68ySbiXfc6vzq5"},
    {"name": "Ultimate Reggae", "id":"37i9dQZF1DX2oc5aN4UDfD"},
    {"name": "This Is Nicki Minaj", "id":"37i9dQZF1DZ06evO0684jS"},
    {"name": "RAP FRANCAIS 2024 HIT RAP CORNER", "id":"4qKKSgcuPJ9D1DGwAAqquG"},
    {"name": "Playlist 2023", "id":"03LKISStS5uOEvt5cRDnIZ"},
    {"name": "Playlist Ganteng", "id":"3CtvjBiuINIH1HARTEX6iZ"},
    {"name":"This Is Micheal Jackson","id":"37i9dQZF1DZ06evO1SVXaM"},
    {"name":"Johnny Hallyday Best of","id":"4EOvzH4guWjtLbjfxMPLO4"},
    {"name":"Hot Gym Girls Playlist","id":"0orDWyz3Wv1XDpO0YuiRw1"},
    {"name":"Mega Pop Mix","id":"37i9dQZF1DX9L93gfg5cPa"},
    {"name":"Frozen Official Playlist","id":"37i9dQZF1DXeapRjZhqZ07"},
    {"name":"mogging playlist","id":"3QZBoyUHfjxos7LP6s6xtJ"},
    {"name":"death mental playlist – 50 classics ","id":"7CxhrkwPKNZhkIBj2d5tcO"},
    {"name":"Playlist calme Marine","id":"3qXovUfQEZS2BrfgcM2pxr"},
    {"name": "Playlists for when your in love..", "id":"1vihDVaPbp5g2UmQOmgics"},
    {"name":"Country Music 2024", "id":"0v5AneHQFa5FYp94PCiz3e"},
    {"name":"G2 Esports", "id":"37i9dQZF1DXdp5YOcv5TSe"},
    {"name":"Rap FR", "id":"3vZYzaSfr9HvjaIivjHyAC"},
    {"name":"Playlist pra fuder gostosinho", "id":"61F2LgLFIpAneBmLCtOnwd"},
    {"name":"Playlist for dancers", "id":"6YOTa2JPtWJDPjX3xJr4ts"},
    {"name":"Playlist Sertanejo 2024", "id":"7ksn7Z9ph9h7G5aeDQWWYU"},
    {"name":"8D Music 2024 8D Audio | 8D Songs by 8D Tunes", "id":"2ULLEdMWHTYLEhNbaclKwS"}
    ]
API_URL = "https://api.spotify.com"
API_CLIENT_ID = "0712177e05fb45afb97e5b09b67ca832"
API_CLIENT_SECRET = "001ec7ea64b241cd83e1d805c3def5c5"

MONGO_URI =  "mongodb+srv://SDCr7AqKRHFk6YEh:XjBIRuxMb3nHurPD@cluster0.deqk5dg.mongodb.net/"
DB_NAME = "Spotify"#YOU SHOULD HAVE CREATED THIS DATABASE ON YOUR CLUSTER
COLLECTION_NAME = "spotify"#YOU SHOULD HAVE CREATED THIS COLLECTION TOO

